import type { AuthSessionState } from '../../src/features/auth/context/authStore';
import type { DashboardState } from '../../src/features/dashboard/context/dashboardStore';

export const createAuthSessionState = (overrides: Partial<AuthSessionState> = {}): AuthSessionState => ({
  status: 'authenticated',
  user: {
    id: 'user-1',
    name: 'Test User',
    email: 'test@example.com',
    role: 'COMMANDER',
  },
  error: null,
  isSubmitting: false,
  isAuthenticated: true,
  isCommander: true,
  login: async () => {},
  register: async () => ({
    id: 'user-2',
    name: 'Registered User',
    email: 'registered@example.com',
    role: 'VIEWER',
  }),
  logout: () => {},
  clearError: () => {},
  ...overrides,
});

export const createDashboardState = (overrides: Partial<DashboardState> = {}): DashboardState => ({
  status: {
    id: 'robot-1',
    position: { x: 2, y: 3 },
    battery: 88,
    status: 'IDLE',
  },
  map: {
    width: 4,
    height: 4,
    grid: [
      [0, 0, 0, 0],
      [0, 1, 0, 0],
      [0, 0, 0, 0],
      [0, 0, 0, 0],
    ],
  },
  sensors: {
    N: 1,
    S: 2,
    E: 3,
    W: 4,
    lidar: [1, 2, 3, 4],
  },
  telemetry: { heading: 90 },
  error: null,
  loading: false,
  busy: false,
  telemetryState: 'Live',
  targetX: 2,
  targetY: 3,
  lidarSummary: { min: 1, max: 4, average: 2.5 },
  lastUpdatedAt: Date.now(),
  lastTelemetryAt: Date.now(),
  telemetryPacketCount: 4,
  isPolling: false,
  connectionHealth: 'Healthy',
  backendStatus: 'healthy',
  backendState: 'Healthy',
  backendIssueMessage: null,
  telemetryStatus: 'live',
  statusPollIntervalMs: 5000,
  telemetrySignalLostMs: 12000,
  telemetryReconnectAttempt: 0,
  telemetryIssueMessage: null,
  commandAuditItems: [],
  statusAuditItems: [],
  auditLoading: false,
  auditError: null,
  loadAuditHistory: async () => {},
  setTargetX: () => {},
  setTargetY: () => {},
  loadDashboard: async () => {},
  submitMove: async () => {},
  submitReset: async () => {},
  ...overrides,
});
