name: Frontend CI

on:
  push:
    branches:
      - master
      - feat/**
      - fix/**
      - refactor/**
  pull_request:

jobs:
  frontend-build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint frontend
        run: npm run lint --workspace frontend

      - name: Build frontend
        run: npm run build --workspace frontend
